// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdaHWHfMDV6kA3ACS4cisYOYC7sP4Nf44',
    appId: '1:15812138698:web:f9e0d905d23ba433f98633',
    messagingSenderId: '15812138698',
    projectId: 'pearl-bags-8439d',
    authDomain: 'pearl-bags-8439d.firebaseapp.com',
    storageBucket: 'pearl-bags-8439d.firebasestorage.app',
    measurementId: 'G-LFG9HRPT21',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDChzWIx3_V37Ln_AGQ9qeI9DHipE2vt4w',
    appId: '1:15812138698:android:ac76407aad673284f98633',
    messagingSenderId: '15812138698',
    projectId: 'pearl-bags-8439d',
    storageBucket: 'pearl-bags-8439d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBDOyVYzVP9ookInfPsbCq9KjLc9lW-Xk',
    appId: '1:15812138698:ios:a9ec78dd9d6e0c2df98633',
    messagingSenderId: '15812138698',
    projectId: 'pearl-bags-8439d',
    storageBucket: 'pearl-bags-8439d.firebasestorage.app',
    iosBundleId: 'com.example.foodWebsite',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBDOyVYzVP9ookInfPsbCq9KjLc9lW-Xk',
    appId: '1:15812138698:ios:a9ec78dd9d6e0c2df98633',
    messagingSenderId: '15812138698',
    projectId: 'pearl-bags-8439d',
    storageBucket: 'pearl-bags-8439d.firebasestorage.app',
    iosBundleId: 'com.example.foodWebsite',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdaHWHfMDV6kA3ACS4cisYOYC7sP4Nf44',
    appId: '1:15812138698:web:097671b6198863baf98633',
    messagingSenderId: '15812138698',
    projectId: 'pearl-bags-8439d',
    authDomain: 'pearl-bags-8439d.firebaseapp.com',
    storageBucket: 'pearl-bags-8439d.firebasestorage.app',
    measurementId: 'G-K01P3ZVLNS',
  );
}